// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metadata.sql

package dbgen

import (
	"context"
)

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM app_metadata WHERE key = $1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
